frontend/modules/product/models/ProductVariation.php
<?php

namespace frontend\modules\product\models;

use frontend\modules\core\behaviors\LangBehavior;
use frontend\queries\ActiveQuery;
use frontend\modules\product\helpers\CartDTO;
use yii\helpers\ArrayHelper;
use frontend\modules\core\models\Setting;
use frontend\modules\product\helpers\CartHelper;

/**
 * Frontend product variation model extends common product variation model.
 */
class ProductVariation extends \common\models\product\ProductVariation
{
    private $fullprice = null;

    /**
     * Url placeholders.
     *
     * @var string
     */
    const URL_PLACEHOLDERS = 'http://via.placeholder.com/';

    /**
     * {@inheritdoc}
     *
     * @return array
     */
    public function behaviors()
    {
        return ArrayHelper::merge(
            parent::behaviors(),
            [
                [
                    'class' => LangBehavior::className(),
                    'langModel' => ProductVariationLangField::className(),
                    'modelForeignKey' => 'product_variation_id',
                    'attributes' => [
                        'name',
                        'description',
                        'short_description',
                    ],
                ]
            ]
        );
    }

    /**
     * {@inheritdoc}
     *
     * @return \frontend\queries\ActiveQuery
     */
    public static function find()
    {
        return new ActiveQuery(get_called_class());
    }

    /**
     * Get product variation image preview.
     *
     * @param int $width Width preview placeholder.
     * @param int $height Width preview placeholder.
     * @return string
     */
    public function getImagePreview($width = 100, $height = 100)
    {
        return ($this->images) ? $this->images[ 0 ]->getUrlImage() : self::URL_PLACEHOLDERS . "{$width}x{$height}";
    }

    /**
     * Check if variation has preview.
     *
     * @return bool
     */
    public function isHasPreview()
    {
        if ($this->images) {
            return true;
        }

        return false;
    }

    /**
     * Get variation preview without placeholder.
     *
     * @return string|null
     */
    public function getPreviewWithoutPlaceholder()
    {
        if ($this->isHasPreview()) {
            return $this->images[ 0 ]->getUrlImage();
        }

        return null;
    }

    /**
     * Generate Data transfer object for cart.
     *
     * @param int $count Count porducts
     * @return \frontend\modules\product\helpers\CartDTO
     */
    public function generateStructureToCart($id, $count)
    {
        $price = ($this->promotion) ? $this->promotion->price : $this->price->price;

        $cartDTO = new CartDTO();

        $cartDTO->productVariationId = $id;
        $cartDTO->productVariationName = $this->name;
        $cartDTO->count = $count;
        $cartDTO->price = self::viewFormatPrice($this->price->price);
        $cartDTO->promotionPrice = ($this->promotion) ? self::viewFormatPrice($this->promotion->price) : null;

        $cartDTO->totalPrice = self::viewFormatPrice($price * $count);

        return $cartDTO;
    }

    public function getMaxCountForCart()
    {
        $product = CartHelper::getProductById($this->id);

        // Товар не находится в корзине
        if (!$product) {
            // обработка пака
            if ($this->isProductAnPack()) {
                $mainPackProductVariation = $this->product->mainPackProduct->getProductVariations()->with('inventorie')->one();

                if (!$mainPackProductVariation || !$mainPackProductVariation->inventorie) {
                    return 0;
                }

                if ($mainPackProductVariation->inventorie->count) {
                    return floor($mainPackProductVariation->inventorie->count / $this->inventorie->count);
                }

                return 0;
            }

            if ($this->isProductSet()) {
                return $this->product->countSet;
            }

            return $this->inventorie->count;
        // Товар находится в корзине
        } else {
            // обработка пака
            if ($this->isProductAnPack()) {
                $mainPackProductVariation = $this->product->mainPackProduct->getProductVariations()->with('inventorie')->one();

                if (!$mainPackProductVariation || !$mainPackProductVariation->inventorie) {
                    return 0;
                }

                if ($mainPackProductVariation->inventorie->count) {
                    return floor($mainPackProductVariation->inventorie->count / $this->inventorie->count) - $product->count;
                }

                return 0;
            }

            if ($this->isProductSet()) {
                return $this->product->countSet - $product->count;
            }

            $count = $this->inventorie->count - $product->count;

            if ($count) {
                return $count;
            }

            return 0;
        }
    }

    public function isProductSet() {
        return $this->product->isProductSet();
    }

    /**
     * Get product other variations.
     *
     * @return \frontend\modules\product\models\ProductVariations[]
     */
    public function getOtherProductVariations()
    {
        return static::find()
            ->where(['product_id' => $this->product_id])
            ->andWhere(['<>', 'id', $this->id])
            ->active()
            ->all();
    }

    public function getIdForCart()
    {
        return str_pad($this->id, 10, 0, STR_PAD_LEFT);
    }

    /**
     * Find active product variations by ids.
     *
     * @param int[] Product variation ids
     * @return \frontend\modules\product\models\ProductVariations[]
     */
    public static function getActiveProductVariationsByIds($ids)
    {
        return static::find()
            ->with('product')
            ->where(['id' => $ids])
            ->active()
            ->all();
    }

    public function getFullPrice() {
        if ($this->fullprice!=null) return $this->fullprice;

        $obj = new \stdClass();
        $obj->price = $this->price?$this->price->price:null;
        $obj->promotion = $this->promotion?$this->promotion->price:null;
        $obj->finalprice = $obj->promotion?$obj->promotion:$obj->price;

        $this->fullprice = $obj;

        return $this->fullprice;
    }

    /**
     * Check if product has pack item
     *
     * @return bool
     */
    public function isProductAnPack()
    {
        return $this->product->isAnPack();
    }

    /**
     * Check is this product variation has double price.
     *
     * @return bool
     */
    public function isHasDoublePrice()
    {
        $count = ProductPromotion::find()
            ->joinWith(['productVariation variation', 'productVariation.product masterProduct'])
            ->where([
                'masterProduct.id' => $this->product_id,
                'variation.active' => 1,
            ])
            ->groupBy('price')
            ->count();

        if ($count > 1) {
            return true;
        }

        $count = ProductPrice::find()
            ->joinWith(['productVariation variation', 'productVariation.product masterProduct'])
            ->where([
                'masterProduct.id' => $this->product_id,
                'variation.active' => 1,
            ])
            ->groupBy('price')
            ->count();

        if ($count > 1) {
            return true;
        }

        return false;
    }

    /**
     * Get double price for products.
     *
     * @return string
     */
    public function getDoublePrice()
    {
        $count = ProductPromotion::find()
            ->joinWith(['productVariation variation', 'productVariation.product masterProduct'])
            ->where([
                'masterProduct.id' => $this->product_id,
                'variation.active' => 1,
            ])
            ->groupBy('price')
            ->count();

        if ($count > 1) {
            $query = ProductPromotion::find()
                ->joinWith('productVariation.product masterProduct')
                ->where(['masterProduct.id' => $this->product_id])
                ->groupBy('price');

            $min = $query->min('price');
            $max = $query->max('price');
        } else {
            $query = ProductPrice::find()
                ->joinWith('productVariation.product masterProduct')
                ->where(['masterProduct.id' => $this->product_id])
                ->groupBy('price');

            $min = $query->min('price');
            $max = $query->max('price');
        }

        $currency = Setting::value('product.shop.currency');

        return $currency . self::viewFormatPrice($min) . ' - ' . $currency . self::viewFormatPrice($max);
    }

    public function getViewFullPrice() {
        return $this->fullPrice->finalprice;
    }

    public function getViewNumberFormatFullPrice() {
        return self::viewFormatPrice($this->viewFullPrice);
    }

    public static function viewFormatPrice($value) {
        return number_format($value,2, '.', '');
    }

    public function getPriceDiscount() {
        return $this->price?$this->price->price:0;
    }

    public function getIsDiscount() {
        return $this->promotion && $this->promotion->price;
    }

    // =============================================================== Relations ========================================================

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProduct()
    {
        return $this->hasOne(Product::className(), ['id' => 'product_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPreview()
    {
        return $this->hasOne(ProductImage::className(), ['product_variation_id' => 'id'])->orderBy(['sort' => SORT_ASC]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getImages()
    {
        return $this->hasMany(ProductImage::className(), ['product_variation_id' => 'id'])->orderBy(['sort' => SORT_ASC]);

frontend/modules/product/controllers/ProductCategoryController.php
<?php

namespace frontend\modules\product\controllers;

use backend\modules\product\models\Product;
use frontend\modules\core\controllers\FrontController;
use frontend\modules\product\models\forms\ProductFilterForm;
use frontend\modules\product\models\ProductCategory;
use Yii;
use yii\helpers\Url;
use yii\web\NotFoundHttpException;
use yii\data\ActiveDataProvider;
use frontend\modules\product\models\ProductVariation;
use frontend\modules\core\models\CorePage;

/**
 * Frontend product category controller.
 */
class ProductCategoryController extends FrontController
{
    /**
     * Display products in category.
     *
     * @throws NotFoundHttpException If nesting slugs violated
     * @param string $slug Slug category
     * @return mixed
     */
    public function actionIndex($slug)
    {
        if (!ProductCategory::checkNestingSlugs($slug)) {
            throw new NotFoundHttpException('Product category not found');
        }

        $category = $this->findCategoryBySlug(ProductCategory::getLastCategorySlug($slug));

        $this->setMetaTitle($category->meta_title);
        $this->setMetaKeywords($category->meta_keywords);
        $this->setMetaDescription($category->meta_description);

        $categoryIds = ProductCategory::getChildrenIds($category);

        $dataProviderVariations = new ActiveDataProvider([
            'query' => ProductFilterForm::filter(
                  ProductVariation::find()
                      ->alias('default_variations')
                      ->with('preview', 'price', 'promotion')
                      ->leftJoin(Product::tableName().' product', 'product.default_variation_id = default_variations.id')
                      ->leftJoin(ProductVariation::tableName().' variations', 'variations.product_id = product.id')
                      ->joinWith('product.productRelationCategories prodRelCat')
                      ->where(['variations.active' => 1, 'product.active' => 1, 'prodRelCat.product_category_id' => $categoryIds])
                      ->groupBy('default_variations.product_id'),
                  $categoryIds
            ),
            'pagination' => [
                'pageSize' => 28,
                'validatePage' => false
            ],
        ]);
        if (Yii::$app->request->isAjax) {
            return $this->renderPartial('index-ajax', [
                'category' => $category,
                'dataProviderVariations' => $dataProviderVariations,
                'categorySlugs' => $slug,
            ]);
        } else {
            return $this->render('index', [
                'category' => $category,
                'dataProviderVariations' => $dataProviderVariations,
                'categorySlugs' => $slug,
                'categoryIds' => $categoryIds
            ]);
        }
    }

    public function actionShop()
    {
        $modelCategories = $this->findCategoryByRoot();

        $categoryIds = [];
        foreach ($modelCategories as $category) {
            $categoryIds = array_merge($categoryIds, ProductCategory::getChildrenIds($category));
        }

        $dataProviderVariations = new ActiveDataProvider([
            'query' => ProductFilterForm::filter(
                ProductVariation::find()
                    ->alias('default_variations')
                    ->with('preview', 'price', 'promotion')
                    ->leftJoin(Product::tableName().' product', 'product.default_variation_id = default_variations.id')
                    ->leftJoin(ProductVariation::tableName().' variations', 'variations.product_id = product.id')
                    ->joinWith('product.productRelationCategories prodRelCat')
                    ->where(['variations.active' => 1, 'product.active' => 1, 'prodRelCat.product_category_id' => $categoryIds])
                    ->groupBy('default_variations.product_id'),
                $categoryIds
            ),
            'pagination' => [
                'pageSize' => 28,
                'validatePage' => false
            ],
        ]);
        if (Yii::$app->request->isAjax) {
            return $this->renderPartial('index-ajax', [
                'dataProviderVariations' => $dataProviderVariations,
                'categorySlugs' => 'shop',
            ]);
        }

        if ($page = CorePage::findShopPage()) {
            $this->setMetaTitle($page->meta_title);
            $this->setMetaDescription($page->meta_description);
            $this->setMetaKeywords($page->meta_keywords);
        }

        return $this->render('shop', [
            'dataProviderVariations' => $dataProviderVariations,
            'categorySlugs' => 'shop',
            'categoryIds' => $categoryIds
        ]);
    }

    /**
     * Show new arrivals products.
     *
     * @return mixed
     */
    public function actionNews()
    {
        $modelCategories = $this->findCategoryByRoot();

        $categoryIds = [];
        foreach ($modelCategories as $category) {
            $categoryIds = array_merge($categoryIds, ProductCategory::getChildrenIds($category));
        }

        $dataProviderVariations = new ActiveDataProvider([
            'query' => ProductFilterForm::filter(
                ProductVariation::find()
                    ->alias('default_variations')
                    ->with('preview', 'price', 'promotion')
                    ->leftJoin(Product::tableName().' product', 'product.default_variation_id = default_variations.id')
                    ->leftJoin(ProductVariation::tableName().' variations', 'variations.product_id = product.id')
                    ->joinWith('product.productRelationCategories prodRelCat')
                    ->where(['variations.active' => 1, 'product.active' => 1, 'prodRelCat.product_category_id' => $categoryIds])
                    ->groupBy('default_variations.product_id')
                    ->orderBy('created_at', SORT_DESC),
                $categoryIds
            ),
            'pagination' => [
                'pageSize' => 28,
                'validatePage' => false
            ],
        ]);

        if (Yii::$app->request->isAjax) {

            return $this->renderPartial('index-ajax', [
                'dataProviderVariations' => $dataProviderVariations,
                'categorySlugs' => 'shop',
            ]);
        }

        if ($page = CorePage::findShopNewPage()) {
            $this->setMetaTitle($page->meta_title);
            $this->setMetaDescription($page->meta_description);
            $this->setMetaKeywords($page->meta_keywords);
        }


        return $this->render('shop', [
            'dataProviderVariations' => $dataProviderVariations,
            'categorySlugs' => 'shop',
            'categoryIds' => $categoryIds
        ]);
    }

    /**
     * Find active category by slug.
     *
     * @throws NotFoundHttpException If not found category
     * @param string $slug Category slug
     * @return \frontend\modules\product\models\ProductCategory
     */
    private function findCategoryBySlug($slug)
    {
        $category = ProductCategory::find()
            ->where(['slug' => $slug])
            ->active()
            ->one();

        if (!$category) {
            throw new NotFoundHttpException('Product category not found');
        }

        return $category;
    }

    private function findCategoryByRoot()
    {
        $categorys = ProductCategory::find()
            ->where(['parent_id' => 0])
            ->active()
            ->all();

        if (!$categorys) {
            throw new NotFoundHttpException('Product category not found');
        }

        return $categorys;
    }
}

frontend/modules/product/views/product-category/index-ajax.php
<?php

use yii\widgets\ListView;

?>


<?= ListView::widget([
    'dataProvider' => $dataProviderVariations,
    'itemView' => 'product_item',
    'layout' => '{items}',
    'summary' => false,
    'itemOptions' => [
        'tag' => false
    ],
    'options' => [
        'tag' => false
    ],
    'viewParams' => compact('categorySlugs'),
]); ?>

frontend/modules/product/views/product-category/index.php
<?php

use frontend\modules\product\assets\CategoryAsset;
use frontend\modules\product\widgets\ProductCategoriesMenu;
use frontend\modules\product\widgets\ProductFilters;
use frontend\modules\product\widgets\ProductLoadNextPage;
use frontend\modules\product\widgets\ProductSort;
use yii\widgets\LinkPager;
use yii\widgets\ListView;

/** \yii\web\View $this */
/** \yii\data\ActiveDataProvider $dataProviderVariations */
/** \frontend\modules\product\models\ProductCategory $category */
/** string $categorySlugs */

CategoryAsset::register($this);

$this->bodyClass = 'shop-page';
?>

<div class="shop-page__main-content-wrapper">
    <div class="container">
        <div class="shop-page__adaptive-header">
            <h1><?= $category->parent?$category->parent->name:''; ?></h1>
            <div class="shop-page__category-chosen-adaptive"><?= $category->name; ?> <span>(<?=  $dataProviderVariations->totalCount ?>)</span></div>
        </div>
    </div>
    <div class="container-fluid filters-wrapper" id="filters-wrapper">
        <div class="container">
            <?= ProductFilters::widget([
                'category' => $category,
                'formAction' => $categorySlugs,
                'categoryIds' => $categoryIds
            ]) ?>
        </div>
    </div>

    <div class="container-fluid category-adaptive-wrapper" id="category-adaptive-wrapper">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="row" id="accordion2">
                        <?= ProductCategoriesMenu::widget([
                                'template' => 'product-categories-menu-mobile'
                        ]); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="shop-page__main-content container">
        <div class="shop-page__main-part row">
            <aside class="col-xl-4">
                <div id="accordion">
                    <?= ProductCategoriesMenu::widget(); ?>
                </div>
            </aside>
            <main class="col-xl-8">
                <div class="shop-page__main-head">
                    <div class="shop-page__category-chosen"><?= $category->name; ?> <span>(<?=  $dataProviderVariations->totalCount ?>)</span></div>
                    <div class="shop-page__sort">
                        <div class="shop-page__category-adaptive"><?= Yii::t('product', 'category'); ?></div>
                        <div class="shop-page__filter"><?= Yii::t('product', 'Filter') ?></div>
                        <?= ProductSort::widget([
                            'formAction' => $categorySlugs,
                        ]) ?>
                    </div>
                </div>
                <div class="shop-page__shop-items">
                    <div class="shop-items row list-catalog">

                        <?= ListView::widget([
                            'dataProvider' => $dataProviderVariations,
                            'itemView' => 'product_item',
                            'layout' => '{items}',
                            'summary' => false,
                            'itemOptions' => [
                                'tag' => false
                            ],
                            'options' => [
                                'tag' => false
                            ],
                            'viewParams' => compact('categorySlugs'),
                        ]); ?>

                    </div>
                </div>
                <?= ProductLoadNextPage::widget([
                    'dataProvider' => $dataProviderVariations
                ]) ?>
                <?= LinkPager::widget([
                    'pagination' => $dataProviderVariations->pagination,
                    'disableCurrentPageButton' => true,
                    'options' => [
                        'class' => 'pagination d-none'
                    ]
                ]) ?>
            </main>
        </div>
    </div>
</div>

frontend/modules/product/views/product-category/product_item.php
<?php

use frontend\modules\core\models\Setting;
use yii\helpers\Url;
use frontend\modules\product\models\ProductVariation;

/** @var \frontend\modules\core\components\View $this */
/** @var \frontend\modules\product\models\ProductVariation $model */
/** @var string $slugMaster */

$slugMaster = $model->product->slug;

?>

<div class="shop-row-margin col-xl-3 col-lg-3 col-md-4 col-sm-4 col-6">
    <a class="shop-item" href="<?= Url::toRoute(['/product/product/index', 'slug' => $slugMaster]); ?>" title="<?= $model->name; ?>">
        <div class="shop-item-img" style="background-image: url(<?= $model->getImagePreview(170, 170) ?>)"></div>
        <div class="shop-item-body">
            <p class="shop-item__item-title"><?= $model->name; ?></p>
            <div class="shop-item__item-price-wrapper">

                <?php if ($model->isHasDoublePrice()) : ?>

                    <p class="shop-item__item-price"><?= $model->doublePrice ?></p>

                <?php else : ?>

                    <?php if ($model->isDiscount): ?>

                        <p class="shop-item__item-share-price"><?= Setting::value('product.shop.currency') ?><?= ProductVariation::viewFormatPrice($model->priceDiscount) ?></p>

                    <?php endif; ?>

                    <p class="shop-item__item-price"><?= Setting::value('product.shop.currency') ?><?= $model->viewNumberFormatFullPrice ?></p>

                <?php endif; ?>

            </div>
            <p class="shop-item__item-zz"><?= Yii::t('product', 'plus 19% VAT.') ?></p>
        </div>
    </a>
</div>

frontend/modules/product/views/product-category/shop.php
<?php

use frontend\modules\product\assets\CategoryAsset;
use frontend\modules\product\widgets\ProductCategoriesMenu;
use frontend\modules\product\widgets\ProductFilters;
use frontend\modules\product\widgets\ProductLoadNextPage;
use frontend\modules\product\widgets\ProductSort;
use yii\widgets\LinkPager;
use yii\widgets\ListView;

/** \yii\web\View $this */
/** \yii\data\ActiveDataProvider $dataProviderVariations */
/** \frontend\modules\product\models\ProductCategory $category */
/** string $categorySlugs */

CategoryAsset::register($this);

$this->bodyClass = 'shop-page';
?>

<div class="shop-page__main-content-wrapper">
    <div class="container">
        <div class="shop-page__adaptive-header">
            <div class="shop-page__category-chosen-adaptive"><?= Yii::t('core', 'Shop') ?> <span>(<?=  $dataProviderVariations->totalCount ?>)</span></div>
        </div>
    </div>
    <div class="container-fluid filters-wrapper" id="filters-wrapper">
        <div class="container">
            <?= ProductFilters::widget([
                'formAction' => $categorySlugs,
                'categoryIds' => $categoryIds
            ]) ?>
        </div>
    </div>

    <div class="container-fluid category-adaptive-wrapper" id="category-adaptive-wrapper">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="row" id="accordion2">
                        <?= ProductCategoriesMenu::widget([
                                'template' => 'product-categories-menu-mobile'
                        ]); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="shop-page__main-content container">
        <div class="shop-page__main-part row">
            <aside class="col-xl-4">
                <div id="accordion">
                    <?= ProductCategoriesMenu::widget(); ?>
                </div>
            </aside>
            <main class="col-xl-8">
                <div class="shop-page__main-head">
                    <div class="shop-page__category-chosen"><?= Yii::t('core', 'Shop') ?> <span>(<?=  $dataProviderVariations->totalCount ?>)</span></div>
                    <div class="shop-page__sort">
                        <div class="shop-page__category-adaptive"><?= Yii::t('product', 'category'); ?></div>
                        <div class="shop-page__filter"><?= Yii::t('product', 'Filter') ?></div>
                        <?= ProductSort::widget([
                            'formAction' => $categorySlugs,
                        ]) ?>
                    </div>
                </div>
                <div class="shop-page__shop-items">
                    <div class="shop-items row list-catalog">

                        <?= ListView::widget([
                            'dataProvider' => $dataProviderVariations,
                            'itemView' => 'product_item',
                            'layout' => '{items}',
                            'summary' => false,
                            'itemOptions' => [
                                'tag' => false
                            ],
                            'options' => [
                                'tag' => false
                            ],
                            'viewParams' => compact('categorySlugs'),
                        ]); ?>

                    </div>
                </div>
                <?= ProductLoadNextPage::widget([
                    'dataProvider' => $dataProviderVariations
                ]) ?>
                <?= LinkPager::widget([
                    'pagination' => $dataProviderVariations->pagination,
                    'disableCurrentPageButton' => true,
                    'options' => [
                        'class' => 'pagination d-none'
                    ]
                ]) ?>
            </main>
        </div>
    </div>
</div>